POISSON_PROCESS_NEW_REQUESTS_LAMBDA = 100
PARETO_PROCESS_NEW_FILE_SIZE_A = 2
PARETO_PROCESS_NEW_FILE_SIZE_M = 1
PARETO_PROCESS_FILE_POPULARITY_A = 1
PARETO_PROCESS_FILE_POPULARITY_M = 1
LOGNORMAL_PROCESS_ARRIVE_AT_QUEUE_MEAN = 0.5
LOGNORMAL_PROCESS_ARRIVE_AT_QUEUE_SIGMA = 0.4

TOTAL_NO_OF_FILES = 10000
INSTITUTIONAL_BANDWIDTH = 1000
ACCESS_LINK_BANDWIDTH = 15
TOTAL_TIME_TO_RUN = 10
CACHE_CAPACITY = 50
CACHE_MAX_ALLOWED_FILE_SIZE = 10
SIMULATOR_ITERATIONS = 15